version: '3'
services:
  message:
    image: asakchris/aws-service-discovery-message:1.0-SNAPSHOT
    ports:
      - "8010:8000"
      - "8011:8001"
  random:
    image: asakchris/aws-service-discovery-random:1.0-SNAPSHOT
    ports:
      - "8020:8000"
      - "8021:8001"
  welcome:
    image: asakchris/aws-service-discovery-welcome:1.0-SNAPSHOT
    environment:
      - MESSAGE_SERVICE_URL=http://message:8010/
      - RANDOM_SERVICE_URL=http://random:8020/
    ports:
      - "8000:8000"
      - "8001:8001"