version: '3'
services:
  message:
    image: ${REPOSITORY_URL}/aws-service-discovery-message:1.0-SNAPSHOT
    ports:
      - "8010:8000"
      - "8011:8001"
  random:
    image: ${REPOSITORY_URL}/aws-service-discovery-random:1.0-SNAPSHOT
    ports:
      - "9010:8000"
      - "9011:8001"
  welcome:
    image: ${REPOSITORY_URL}/aws-service-discovery-welcome:1.0-SNAPSHOT
    environment:
      - MESSAGE_SERVICE_URL=http://message:8000/api/v1/message
      - RANDOM_SERVICE_URL=http://random:8000/api/v1/random
    ports:
      - "8000:8000"
      - "8001:8001"
  swagger:
    image: ${REPOSITORY_URL}/aws-service-discovery-swagger:1.0-SNAPSHOT
    ports:
      - "3888:8000"
      - "3889:8001"