server:
  port: 8030
  servlet:
    context-path: /api/v1/random
management:
  server:
    port: 8031
  endpoints:
    web:
      exposure:
        include: health, info, metrics

spring:
  application:
    name: Random