server:
  port: 8020
  servlet:
    context-path: /api/v1/message
management:
  server:
    port: 8021
  endpoints:
    web:
      exposure:
        include: health, info, metrics

spring:
  application:
    name: Message